# Generated by Django 5.1.7 on 2025-04-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_updated_at_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('products', models.ManyToManyField(related_name='Product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
